# ==========================================
# BOTNOVOTESTEATT v5.0.0 - ADVANCED CONFIGURATION
# AI-Human Collaborative SimpleMMO Bot
# ==========================================

# === CORE APPLICATION SETTINGS ===
app:
  name: "BotNovoTesteAtt"
  version: "5.0.0"
  environment: "development"  # development, production
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  headless: false  # Run browser in headless mode

# === AI CAPTCHA RESOLVER (Future Implementation) ===
ai_captcha:
  enabled: false  # Will be enabled when implemented
  confidence_threshold: 0.8  # Minimum confidence for captcha resolution (0.0-1.0)
  resolution_timeout: 10.0  # Maximum seconds for captcha resolution
  save_training_data: false  # Save successful resolutions for training
  training_data_file: "captcha_training_data.json"

  # Detection settings
  detection:
    screenshot_on_detection: true
    auto_retry_attempts: 3
    retry_delay_seconds: 2.0

# === ADVANCED MONITORING SYSTEM ===
monitoring:
  enabled: true
  save_analytics: true
  analytics_file: "bot_analytics.json"

  # Performance tracking
  performance:
    track_actions_per_minute: true
    track_success_rates: true
    track_resource_usage: true
    history_retention_hours: 24

  # Alert system
  alerts:
    enabled: true
    cooldown_seconds: 300  # 5 minutes between same alert

    # Alert thresholds
    thresholds:
      low_success_rate: 70.0  # Percentage
      high_error_rate: 20.0   # Percentage
      low_activity: 1.0       # Actions per minute
      high_memory_mb: 1000.0  # Memory usage in MB

# === MODERN NOTIFICATION SYSTEM ===
notifications:
  enabled: true

  # Discord integration
  discord:
    enabled: false
    webhook_url: ""  # Add your Discord webhook URL here
    username: "SimpleMMO Bot"

    # Notification levels to send to Discord
    levels: ["WARNING", "ERROR", "CRITICAL"]

  # Desktop notifications
  desktop:
    enabled: true
    levels: ["WARNING", "ERROR", "CRITICAL"]
    timeout: 10  # Seconds

# === PLAYWRIGHT WEB AUTOMATION ===
playwright:
  enabled: true
  browser: "chromium"  # chromium, firefox, webkit

  # Browser settings
  browser_settings:
    headless: false
    viewport:
      width: 1280
      height: 720
    user_agent: "auto"  # "auto" for automatic, or specify custom

  # Performance optimizations
  performance:
    page_load_timeout: 30000  # milliseconds
    navigation_timeout: 20000  # milliseconds
    default_timeout: 10000    # milliseconds

# === SIMPLEMMÐž GAME SETTINGS ===
game:
  # URLs
  urls:
    base_url: "https://web.simple-mmo.com"
    travel_url: "https://web.simple-mmo.com/travel"
    login_url: "https://web.simple-mmo.com/login"

  # Game mechanics
  mechanics:
    # Health management
    heal_threshold: 20  # Heal when health below this percentage
    emergency_heal_threshold: 10  # Emergency heal threshold

    # Energy management
    energy_threshold: 10  # Wait when energy below this percentage
    energy_wait_time: 30  # Seconds to wait for energy regen

    # Combat settings
    combat:
      max_fight_duration: 300  # Maximum seconds per fight
      retreat_health_threshold: 15  # Retreat when health below this
      aggressive_mode: false  # More aggressive combat behavior

    # Movement settings
    movement:
      random_steps: true  # Add randomness to movement
      step_delay_min: 1.0  # Minimum seconds between steps
      step_delay_max: 3.0  # Maximum seconds between steps

# === ADVANCED FEATURES ===
features:
  # Core automation features
  smart_error_recovery: true
  automatic_optimization: true
  concurrent_operations: true

  # Safety features
  captcha_detection: true  # Basic detection (advanced AI resolution TBD)
  anti_ban_measures: true
  human_behavior_simulation: true

  # Future AI features (placeholders)
  ai_captcha_resolution: false  # Will be enabled when implemented
  adaptive_behavior: false     # Will be enabled when implemented
  learning_from_failures: false # Will be enabled when implemented

# === DEVELOPMENT SETTINGS ===
development:
  # Debug settings
  debug_mode: false
  verbose_logging: false
  log_to_file: true
  log_file: "bot.log"

  # Testing settings
  test_mode: false
  simulation_speed: 1.0  # Speed multiplier for testing
